env:
  global:
    - CC_TEST_REPORTER_ID=33dec833c8c38b66895abeedd80633f19ad8e08bacf3a2421d1fef5b36ef207f
sudo: false
language: php
php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - hhvm
install:
  - composer install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - if [[ $TRAVIS_PHP_VERSION = 7.* ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
