sudo: false
language: php
php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - hhvm
install:
  - composer install
after_script:
  - if [[ ! $TRAVIS_PHP_VERSION = 5.5* ]]; then CODECLIMATE_REPO_TOKEN=33dec833c8c38b66895abeedd80633f19ad8e08bacf3a2421d1fef5b36ef207f ./vendor/bin/test-reporter
